#!/bin/bash

# paths
#   walk up to find package.json @ ROOT
PWD=$(pwd)

cd `dirname $0`
while [[ ! -e "package.json" ]]; do cd ..; done
ROOT=$(pwd)

ES5=$ROOT/build/es5
NODE_BIN=$ROOT/node_modules/.bin

JS_DIRS="app/ app.js config/ gulpfile.js index.js lib/ run/ test/ views/"

# colors
#   http://www.csc.uvic.ca/~sae/seng265/fall04/tips/s265s047-tips/bash-using-colors.html
C_INFO="\033[1;37;40m"
C_OK="\033[1;30;42m"
C_ERR="\033[1;37;41m"
C_WARN="\033[1;30;43m"
C_CLOSE="\033[0m"

# logging and resolution
function INFO () {
    echo -e "$C_INFO INFO $C_CLOSE $1"
}
function WARN () {
    echo -e "$C_WARN WARN $C_CLOSE $1"
}
function FAIL () {
    echo -e "$C_ERR FAIL $C_CLOSE $1"
    cd $PWD
    exit 1
}
function SUCCEED () {
    echo -e "$C_OK  OK  $C_CLOSE $1"
    cd $PWD
    exit 0
}

#
# EXIT_OR_FORCE <WORD> [<EXITCODE>]
#   WORD = stub which must be entered from console to force
#   EXITCODE = assumed 1
#   `FORCE=true EXIT_OR_FORCE ...` => WASFORCED=1
#   stub entered => WASFORCED=2
#
WASFORCED=0
function EXIT_OR_FORCE() {
    WASFORCED=0

    local WORD=$1
    local EXITCODE=$2
    if [ "$EXITCODE" == "" ]; then
        EXITCODE=1
    fi

    if [ 0 -eq $EXITCODE ]; then
        return
    fi

    if [ "$FORCE" == "true" ]; then
        WAS_FORCED=1
        return
    fi

    # ensure TTY interaction during read
    exec < /dev/tty
    local REQUIRED=$WORD-$(expr $RANDOM % 10)
    read -p "Enter '$REQUIRED' to continue: " ENTERED
    exec <&-

    if [ "$ENTERED" == "$REQUIRED" ]; then
        WAS_FORCED=2
        return
    fi

    exit $EXITCODE
}
