#!/bin/bash

source `dirname $0`/common

# https://github.com/gotwarlost/istanbul#configuring
#   `istanbul help`
#   .istanbul.yml
#   /* istanbul ignore if */
#   /* istanbul ignore else */
#   /* istanbul ignore next */

pushd . > /dev/null
cd $ROOT


npm run compile
CODE=$?

if [[ "$CODE" == "0" ]]; then
    # uses `_mocha`, unlike `npm test`
    NODE_ENV=test $NODE_BIN/istanbul cover $NODE_BIN/_mocha $ES5/test -- --reporter nyan
    CODE=$?
fi

if [[ "$CODE" == "0" ]]; then
    $NODE_BIN/istanbul report
    $NODE_BIN/istanbul check-coverage
    CODE=$?
fi


popd > /dev/null


if [[ "$CODE" != "0" ]]; then
    FAIL "failed to achieve coverage"
fi

SUCCEED "coverage achieved!"
