#!/bin/sh

source `dirname $0`/common

# https://github.com/gotwarlost/istanbul#configuring
#   `istanbul help`
#   .istanbul.yml
#   /* istanbul ignore if */
#   /* istanbul ignore else */
#   /* istanbul ignore next */

pushd . > /dev/null
cd $ROOT

# slightly different than `npm test`
NODE_ENV=test $NODE_BIN/istanbul cover $NODE_BIN/_mocha test -- --reporter nyan
if [[ "$?" != "0" ]]; then
    WARN "failed to run coverage"
fi

$NODE_BIN/istanbul report
$NODE_BIN/istanbul check-coverage
CODE=$?

popd > /dev/null

if [[ "$CODE" != "0" ]]; then
    FAIL "failed to achieve coverage"
fi

SUCCEED "coverage achieved!"
