#!/bin/bash

source `dirname $0`/common

# https://github.com/jsdoc3/jsdoc
#   http://usejsdoc.org/
#   "jsdoc": "3.3.0-beta1"
#   .jsdoc.json

pushd . > /dev/null
cd $ROOT

mkdir -p build
$NODE_BIN/jsdoc -c $ROOT/.jsdoc.json
CODE=$?

popd > /dev/null

if [[ "$CODE" != "0" ]]; then
    FAIL "failed to build doc"
fi

SUCCEED "doc built!"
