#!/bin/bash

source `dirname $0`/common

# https://github.com/jshint/jshint
#   http://jshint.com/docs/options/

pushd . > /dev/null
cd $ROOT

$NODE_BIN/jshint --config .jshintrc $JS_DIRS
CODE=$?

popd > /dev/null

if [[ "$CODE" != "0" ]]; then
    FAIL "failed to lint"
fi

SUCCEED "it has linted!"


# https://github.com/eslint/eslint
#   http://eslint.org/docs/user-guide/configuring
#   http://eslint.org/docs/rules/
