#!/bin/sh

source `dirname $0`/common

# ensure Git directory
GIT=$ROOT/.git
if [[ ! -d $GIT ]]; then
    exit 0
fi

# establish Git hooks
echo ensuring .git/hooks
mkdir -p $GIT/hooks
pushd . > /dev/null
cd $GIT/hooks

echo installing .git/hooks
for FILE in common pre-commit; do
    rm -f $FILE
    ln -s $ROOT/run/$FILE .
done

popd > /dev/null
